### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by ezzcodeezzlife** [vaibhavnirmal2001/Search-city-condition#2]
API Key is leaked in app.js

**Comment by vaibhavnirmal2001** [comment]
is there any option to hide these keys?
because Don't want to loose that code

**Comment by ezzcodeezzlife** [comment]
Best practise would be a [ .env file with variables](https://www.npmjs.com/package/dotenv)

Then add the .env file to [ .gitignore](https://git-scm.com/docs/gitignore) file
